# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Donetick Addon
version: "1.1.50"
slug: Donetick
description: Simplify Tasks & Chores, Together.
url: "https://github.com/Donetick/hassio-addons/tree/main/donetick"
arch:
  - armv7
  - aarch64
  - amd64
init: false
map:
  - type: data
    read_only: False
    path: /data
environment:
  DT_SQLITE_PATH: /data/donetick.db
  DT_ENV: selfhosted
ports:
  80/tcp: 8005
  2021/tcp: 2021
webui: http://[HOST]:[PORT:2021]
image: "ghcr.io/donetick/{arch}-hassio-addons"



options:
  telegram_token: ""
  pushover_token: ""
  disable_signup: false
  auth_provider: ""
  oauth2_client_id: ""
  oauth2_client_secret: ""
  oauth2_redirect_uri: ""
  oauth2_auth_url: ""
  oauth2_token_url: ""
  oauth2_user_info_url: ""
  oauth2_name: ""


schema:
  telegram_token: "str?"
  pushover_token: "str?"
  disable_signup: "bool?"
  auth_provider: "str?"
  oauth2_client_id: "str?"
  oauth2_client_secret: "str?"
  oauth2_redirect_uri: "str?"
  oauth2_auth_url: "str?"
  oauth2_token_url: "str?"
  oauth2_user_info_url: "str?"
  oauth2_name: "str?"

